services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chatapp_client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chatapp_server
    ports:
      - "8001:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine
    container_name: chatapp_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: